/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package openapi.api

import openapi.model.UsersGet200Response
import openapi.model.UsersGet400Response
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity

import org.springframework.web.bind.annotation.*

@RestController
interface UsersApi {

    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/api/v1/users"],
            produces = ["application/json"]
    )
    fun usersGet(): ResponseEntity<UsersGet200Response> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
